### ISSUE TITLE
Jam TODO

### ISSUE THREAD

**Issue by nicobarray** [yahwastaken/ludum-dare-43#1]
Dices:
- [x] Random dice results
- [x] Add dices
- [x] Remove dices
- [ ] Impl bad dices (-1 on throw)
- [ ] ~Add random dices~

Game loop:
- [x] Turn phases:
   - [x] Beginning phase (random event between 2/3 cards)
   - [x] Dice Throw phase
   - [x] Act phase (consum dice points to move villagers)
   - [x] End phase (trigger villagers actions)
- [x] Victory (survive and get as much resources as you can to survive winter
- [x] Defeat (all villagers are dead)

Note:
- dice points = *dp*
- block point: *bp*

Places:
- [ ] Market place: trade goods (ex: 1 wood for 1 sheep) (2dp)
_Variating goods and prices between turns_
- [x] Woods: gather +1 wood at the end of turn (1 dp)
_Main resource for the Builder's Hut_
- [x] Mines: gather +1 rock at the end of turn (2 dp)
_Secondary resource for the Builder's Hut_
- [x] Lake: fish +1 food at the end of turn (2dp)
_Each end of turn, villagers need 1 food or have bad dices next turn_
- [x] House: gain +1 temp dice next turn (4dp)
_The villager rests for a turn to do twice as much next turn_
- [x] Watch Tower: 1 bp until next turn (2dp)
_1 block point can be used to counter dangerous events at the beginning of the next turn... if any_
- [ ] Builder's Hut: build +1 building at the end of turn (4dp)
_Can build of places for a price_

Events Cards:
- [x] A new villager is born (+1 villager, -3 food)
- [x] An elderly died (-1 villager)
- [x] Bandit attack ! (-X wood, -Y food)
- [ ] Shuffle Market Place (New prices, new goods)
- [ ] The mine (Add new place)
- [ ] Church of the night (Each night, every villagers outside home are afflicted with -1 on their dices next turn)
- [ ] Good Ale ! (-1 food per villagers, +1 to their dice throws next turn)
